version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drf
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  ipfs:
    image: ipfs/go-ipfs:latest
    restart: always
    ports:
      - '5001:5001'
      - '8080:8080'
    volumes:
      - ipfs_data:/data/ipfs
volumes:
  db_data:
  redis_data:
  ipfs_data:
